### ISSUE TITLE
Issue with navigation

### ISSUE THREAD

**Issue by emahadzimustafic** [emahadzimustafic/modularity-mindfulness#1]
Hello, I can't get my nav to stop crossing my h1. I know it has to do with the flex box, but I don't know what I'm missing. Please help!

I did my web screen CSS before my phone screen CSS, so I had to restart today :(

@thatkidmadrid or @anna-pokhilenko

**Comment by thatkidmadrid** [comment]
Hi Ema,
This is an interesting approach to the activity and I played around and was able to recreate things with the grid you created. The way I have it in the solution doesn't have a grid on the entire body - just the bottom area - but this is actually very interesting and I encourage you to continue this way because it's possible and I was able to do it 👍 

One thing I would start with is to not use `display: contents` in the header. That should get things close on its own. then make your adjustments to match the small screen.

Then add the media query for the appropriate break-point and change the styling to match the next screen size reference

**Comment by emahadzimustafic** [comment]
Thank you Christian, that worked! My CSS is a mess and very long right now, but I'll try to fix it before I submit it.

I'm having issues with figure 3 in col3 row3 - it's not being responsive, and I believe it's because of the nav at the top right. I'm not sure how to fix that. With my approach, would I have to change its font size at a certain point (using media query)?

As for my section/quote (line 218 in CSS code), is there a way I can have it ignore the 3 columns? I tried adding a span CSS code but I don't think it does what I think it does. I don't think we've learned this yet.

**Comment by thatkidmadrid** [comment]
First, I would add `display: flex` and `flex-direction: column` to your `figure`s and `figcaption`s
This will allow you to take advantage of the flex alignment properties.
Using flex-grow on your figcaptions to make sure they are the component that flexbox will adjust to grow (you can set to `flex-grow: 1`) then I think what you have for the links is the right idea using the flex-end, but because the links don't have an adjustable height as they are currently, you can give it an automatic top margin (`margin-top: auto`); This will align them to the bottom. Don't forget to remove the `margin-bottom:0` you used on the last figure while you were troubleshooting.

Something you can do with the quote to have it ignore the grid is to have it span all three columns using `grid-column` or grid-area (in your case, have it in the grid-area "span" that you set up in your grid-template-areas - I would use another name for the area as `span` is a reserved word than can be used to define how many grid sections a grid item can _span_ - for example I just called them `spann` but you can be more clear in your code). Then you can define a max-width on the section, and give it `justify-self:center` you can refer to the [css grid cheat sheet](https://learn-the-web.algonquindesign.ca/topics/css-grid-cheat-sheet/#children) to see what exactly this does

**Comment by emahadzimustafic** [comment]
Thanks Christian, I was able to fix my CSS and add media query. I appreciate it!! I'll make sure to use class time and lab time to ask questions.

I currently have 300 lines of CSS code and I'm having a hard time fixing the padding and margins as I have too many lines of code. I have included all of the important elements, but it's 1-2% different than the screenshots. Will you be able to accept it as is? I can't submit it through markbot.

**Comment by thatkidmadrid** [comment]
Looks good to me!

I'll quickly go over the key things to get the layout at the beginning of class, so that may help you cut down your css, but as it is, it matches the reference and uses the media query effectively so you'll get the grade

**Comment by emahadzimustafic** [comment]
Thank you for your help, enjoy the rest of your Sunday evening!

**Comment by thatkidmadrid** [comment]
Is it ok if I use your activity as an example to the class later of an alternate way to approach the layout?

I won't delve much into the code, just using the browser inspector to show that the same layout can be achieved with a 3x3 grid on the whole page

![Screen Shot 2021-10-04 at 2 59 15 PM](https://user-images.githubusercontent.com/6340290/135908709-a608be3e-86d3-4364-899d-c7fcc0481028.png)
